export default [
  { title: '‎⁨Charles Bridge⁩, ⁨Prague⁩ (⁨Czech Republic⁩) - 2014' },
  { title: '⁨Prague⁩ (⁨Czech Republic⁩) - 2014' },
  { title: 'St. Vito Cathedral, ⁨Prague⁩ (⁨Czech Republic⁩) - 2014' },
  { title: 'John Lennon Wall, ⁨Prague⁩ (⁨Czech Republic⁩) - 2014' },
  { title: 'The Prague Astronomical Clock, ⁨Prague⁩ (⁨Czech Republic⁩) - 2014' },
  { title: '‎⁨‎⁨‎⁨‎⁨Old Town Square⁩, ⁨Prague⁩ (⁨Czech Republic⁩) - 2014' },
  { title: '‎⁨‎⁨‎⁨Cathedral of Barcelona⁩, ⁨Barcelona⁩ ⁨(Spain⁩) - 2014' },
  { title: '‎⁨‎⁨Park Güell⁩, ⁨Barcelona⁩ ⁨(Spain⁩) - 2014' },
  { title: '‎⁨Mercat de la Boqueria⁩, ⁨Barcelona⁩ ⁨(Spain⁩) - 2014' },
  { title: '‎⁨Sagrada Familia⁩ (inside), ⁨Barcelona⁩ (⁨Spain⁩) - 2014' },
  { title: '‎⁨Sagrada Familia⁩ (outside), ⁨Barcelona⁩ ⁨(Spain⁩) - 2014' },
  { title: 'Port Olimpic, ⁨Barcelona⁩ (Spain⁩) - 2014' },
  { title: '‎⁨‎⁨Park De La Ciutadella⁩, ⁨Barcelona⁩ (Spain⁩) - 2014' },
  { title: '‎⁨Arc De Triomf⁩, ⁨Barcelona⁩ (Spain⁩) - 2014' },
  { title: '‎⁨Area Naturale Lago di Chiusi⁩, ⁨Chiusi⁩ (Italy) - 2014' },
  { title: '‎⁨‎⁨Piazza Del Campo⁩, ⁨Siena⁩ (Italy) - 2014' },
  { title: 'San Domenico, Siena (Italy) - 2013' },
  { title: 'Arena di Verona (Italy) - 2013' },
  { title: '‎⁨⁨Neuschwanstein Castle, Bavaria (Germany) - 2013' },
  { title: '‎⁨⁨Neuschwanstein Castle, Bavaria (Germany) - 2013' },
  { title: '‎⁨Innsbruck⁩, ⁨Tyrol⁩ ⁨(Austria⁩) - 2013' },
  { title: '‎⁨⁨Salzburg⁩ ⁨(Austria⁩) - 2013' },
  { title: '‎⁨Historic Centre of the City of Salzburg⁩ (⁨Austria⁩) - 2013' },
  { title: 'Prater, ‎⁨Vienna⁩ ⁨(Austria⁩) - 2013' },
  { title: '‎⁨Klagenfurt, ⁨Carinthia⁩ ⁨(Austria⁩) - 2013' },
  { title: 'Temple of Poseidon⁩, ⁨Lavrio⁩ ⁨(Greece⁩) - 2011' },
  { title: '‎⁨Mycenae⁩ (Greece⁩) - 2011' },
  { title: '‎⁨Parthenon⁩, ⁨Athens⁩ (Greece⁩) - 2011' },
  { title: '‎⁨Temple of Apollo⁩, ⁨Delfoi⁩ (⁨Greece⁩) - 2011' },
  { title: 'Meteora (Greece) - 2011' },
  { title: 'Adriatic Sea - 2011' },
  { title: 'Eiffel Tower, Paris (France) - 2007' },
  { title: 'Moulin Rouge, Paris (France) - 2007' },
  { title: 'Sacré-Cœur, Paris (France) - 2007' }
]
