---
title: "Why Nations Fail"
date: "2020-12-24"
---

In this book, Acemoglu and Robinson answer the question, "Why are some nations rich and others poor?". The authors show that it is man-made political and economic institutions that underlie economic success (or lack thereof) with fascinating and well-documented examples.

Favorite quotes from the book:

> Egypt is poor precisely because it has been ruled by a narrow elite that have organized society for their own benefit at the expense of the vast mass of people.

> Countries such as Great Britain and the United States became rich because their citizens overthrew the elites who controlled power and created a society where political rights were much more broadly distributed, where the government was accountable and responsive to citizens, and where the great mass of people could take advantage of economic opportunities.

> In rich countries, individuals are healthier, live longer, and are much better educated. They also have access to a range of amenities and options in life, from vacations to career paths, that people in poor countries can only dream of. People in rich countries also drive on roads without potholes, and enjoy toilets, electricity, and running water in their houses. They also typically have governments that do not arbitrarily arrest or harass them; on the contrary, the governments provide services, including education, health care, roads, and law and order. Notable, too, is the fact that the citizens vote in elections and have some voice in the political direction their countries take.

> Economic institutions shape economic incentives: the incentives to become educated, to save and invest, to innovate and adopt new technologies, and so on. It is the political process that determines what economic institutions people live under, and it is the political institutions that determine how this process works.

> Tropical diseases obviously cause much suffering and high rates of infant mortality in Africa, but they are not the reason Africa is poor. Disease is largely a consequence of poverty and of governments being unable or unwilling to undertake the public health measures necessary to eradicate them.

> Inequality in the modern world largely results from the uneven dissemination and adoption of technologies...

> Growth thus moves forward only if not blocked by the economic losers who anticipate that their economic privileges will be lost and by the political losers who fear that their political power will be eroded.

> The Black Death and the expansion of world trade after 1600 were both major critical junctures for European powers and interacted with different initial institutions to create a major divergence. Because in 1346 in Western Europe peasants had more power and autonomy than they did in Eastern Europe, the Black Death led to the dissolution of feudalism in the West and the Second Serfdom in the East. Because Eastern and Western Europe had started to diverge in the fourteenth century, the new economic opportunities of the seventeenth, eighteenth, and nineteenth centuries would also have fundamentally different implications for these different parts of Europe. Because in 1600 the grip of the Crown was weaker in England than in France and Spain, Atlantic trade opened the way to the creation of new institutions with greater pluralism in England, while strengthening the French and Spanish monarchs.

> The growth generated by extractive institutions is very different in nature from growth created under inclusive institutions, however. Most important, it is not sustainable. By their very nature, extractive institutions do not foster creative destruction and generate at best only a limited amount of technological progress. The growth they engender thus lasts for only so long.

> This was the beginning of the end of Venetian prosperity. With the main lines of business monopolized by the increasingly narrow elite, the decline was under way. Venice appeared to have been on the brink of becoming the world's first inclusive society, but it fell to a coup. Political and economic institutions became more extractive, and Venice began to experience economic decline.

> Today Venice is rich only because people who make their income elsewhere choose to spend it there admiring the glory of its past. The fact that inclusive institutions can go into reverse shows that there is no simple cumulative process of institutional improvement.

> The fear of creative destruction is the main reason why there was no sustained increase in living standards between the Neolithic and Industrial revolutions.

> Absolutism is not the only form of extractive political institutions and was not the only factor preventing industrialization. Inclusive political and economic institutions necessitate some degree of political centralization so that the state can enforce law and order, uphold property rights, and encourage economic activity when necessary by investing in public services.

> It's only when many individuals and groups have a say in decisions, and the political power to have a seat at the table, that the idea that they should all be treated fairly starts making sense.

> There are natural reasons for this vicious circle. Extractive political institutions lead to extractive economic institutions, which enrich a few at the expense of many. Those who benefit from extractive institutions thus have the resources to build their (private) armies and mercenaries, to buy their judges, and to rig their elections in order to remain in power. They also have every interest in defending the system. Therefore, extractive economic institutions create the platform for extractive political institutions to persist. Power is valuable in regimes with extractive political institutions, because power is unchecked and brings economic riches.

> Because whoever controls the state becomes the beneficiary of this excessive power and the wealth that it generates, extractive institutions create incentives for infighting in order to control power and its benefits, a dynamic that we saw played out in Maya city-states and in Ancient Rome.

> Countries become failed states not because of their geography or their culture, but because of the legacy of extractive institutions, which concentrate power and wealth in the hands of those controlling the state, opening the way for unrest, strife, and civil war.

> What is crucial, however, is that growth under extractive institutions will not be sustained, for two key reasons. First, sustained economic growth requires innovation, and innovation cannot be decoupled from creative destruction, which replaces the old with the new in the economic realm and also destabilizes established power relations in politics.

> Second, the ability of those who dominate extractive institutions to benefit greatly at the expense of the rest of society implies that political power under extractive institutions is highly coveted, making many groups and individuals fight to obtain it. As a consequence, there will be powerful forces pushing societies under extractive institutions toward political instability.

> with a “bird in a cage” analogy for the economy: China's economy was the bird; the party's control, the cage, had to be enlarged to make the bird healthier and more dynamic, but it could not be unlocked or removed, lest the bird fly away.

> Instead, perhaps structuring foreign aid so that its use and administration bring groups and leaders otherwise excluded from power into the decision-making process and empowering a broad segment of population might be a better prospect.
